### ISSUE TITLE
12월 스터디 진행

### ISSUE THREAD

**Issue by Mandory** [Mandory/my-js#14]
@kuongee 님이 지난달에 올려주신 것처럼 매월 계획을 적어놓으면 좋을 것 같아 글 남깁니다.
11월 스터디 진행 글을 보니 소소하지만 계획했던 바를 달성한 것 같아 기분이 좋네요~

이번달도 커밋 3개는 기본 목표로 설정하고, 그 외에 각자 계획한 바가 있으면 댓글로 남겨주시면 좋을 것 같습니다.
추가로 지난달 회고도 같이 남겨주시면 더욱 더 좋을 것 같아요 &#128522;

**Comment by Mandory** [comment]
* 회고
저는 지난달 예상치못한 업무로 인해 커밋 3개를 지키지 못할 줄 알았는데 다행히 지킬 수 있어 뿌듯했습니다.
그리고 11월 스터디 진행글을 다시보며 알고리즘 프로시험에 1번 이상 응시하기로 한 걸 목표로 했다는 사실을.. 새삼 깨닫게 되었네요~ 그래도 어제 시험을 치고 와서 이 목표도 달성한 것 같아 뿌듯합니다 &#128526; 

* 목표
이번달에는 현재 듣고 있는 알고리즘 인강을 3개 이상 듣는 것을 목표로 하겠습니다!
연말이라..... 쉽지 않을 것 같지만 노력해보겠습니다 ~

**Comment by kuongee** [comment]
### 회고
11월 커밋 3개 올리고 개인적인 11월 목표인 이력 정리도 방금 해서 이렇게 회고를 남깁니다~
목표가 있으니까 귀찮은 이력 정리도 어떻게 어떻게 하게 되네요😅  
이번 JavaScript 커밋은 하나의 주제에 대해 공부한 내용을 좀 더 깔끔하게 정리된 문장으로 올려보려고 노력했습니다.
이렇게 하니까 시간은 오래 걸려도 기억에 더 오래 남는 것 같아서 좋았습니다.
그런데 커밋 3개 중 하나는 알고리즘도 풀어서 올려보려고 했지만 너무 쉬운 문제 + 계속된 실패로 올리지 못해서 조금 아쉽습니다.

그래도 이번에도 든든한 스터디원들과 함께 노력할 수 있어서 너무 너무 뿌듯하고 왠지 모를 자신감이 생깁니다💪💪💪

### 목표
- JS - event loop 유튜브 영상 꼭 보고 정리하기
- 커밋 3개 외 프로그래머스 Level 3 이상 문제 하나 풀고 올리기


➕ 건강하게 준비합시당💪
(혹시 저의 이력을 리뷰해주시고 싶으신 분 알려주세요~ 리뷰도 자꾸 받아야한다고 어디서 봐서 부끄럽지만 공개해보겠습니당....)

**Comment by tildev** [comment]
### 회고
11월달은 제게 있어서 다사다난한 달이었습니다.
공부와 병행해야 했는데 잘 되지 않아서 아쉽지만,
 다른방면으로 많은 것을 알았기 때문에 의미있는 시간이었다고 생각합니다. (인생공부:thumbsup:)

하지만 별개로 공부를 안한것은 아쉽기 때문에, 12월은 좀 더 노력해서 두마리 토끼를 다 잡을 수 있도록 노력하겠습니다. :smile:

### 목표
1. DEVIEW 영상 보기
2. Clean Code 책 읽기
