### ISSUE TITLE
2021년 1월 스터디 진행

### ISSUE THREAD

**Issue by kuongee** [Mandory/my-js#27]
안녕하세요🌷
2020년 12월 스터디를 마무리하고 2021년 1월 새로운 스터디를 위한 이슈입니다.

다음달에도 기본 목표를 커밋 3개로 잡고 이외 각자 이루고자 하는 목표가 있다면 공유해주세요~
더불어 지난 12월 한 달 동안의 회고도 같이 남겨주시면 더욱 좋을 거 같습니다.

2020년이 너무 금방 지나간 것 같아 아쉽지만 그래도 잘 마무리하고 새로운 마음으로 2021년을 잘 맞이해봅시당🌞
그리고 우리 스터디원 모두 항상 건강하게 함께 하길 바랍니다🥰

**Comment by tildev** [comment]
# 회고
12월이 눈 깜짝할 새에 지나가네요.
오늘은 12월의 마지막 날입니다.
한 해를 마무리하는 데에 아쉬움이 많지만, 새해에는 아쉬움을 덜 수 있도록 더욱 노력해야 할 것 같아요.

12월 목표한 Clean Code 책 읽기는 초반에는 열심히 했으나, 잘 진행하지는 못했어요. 
우선순위를 잘못 잡아서 그런 것 같습니다. ( 알고리즘 공부 > Clean Code 읽기 )
우선순위를 제대로 생각하여 목표를 정하겠습니다.

모두에게 행복한 2021년 되었으면 좋겠습니다.
2021년도 건강하게 함께 공부해요. 👍 

# 목표
- 알고리즘 매일 1문제 이상 풀기
- 일주일에 5번 이상 커밋하기

**Comment by kuongee** [comment]
# 회고
지난 몇달동안 깃헙에 한달에 3개의 커밋을 꾸준히 올려보려고 하는 노력해왔던 것들이 생각보다 굉장히 뿌듯합니다.
물론 앞으로 더더더 배우고 정리해야할 것들이 많아서 더 열심히 해보고 싶다는 마음이 듭니다.
2021년도 함께 잘 지켜나가요🤩

JS - event loop 영상 보고 정리하기는 목표를 지키기는 했지만 
알고 보니 더 심화 내용이 있다는 사실을 알게 되어😅 아래에 추가 목표로 설정해보려고 합니다.
프로그래머스 LV3는 풀지 못했지만 코딜리티 문제 하나 올린 거으로 대신하려고 합니다.

# 목표
* Event Loop 심화 내용 정리
* 프로그래머스 LV2 / LV3 문제 2문제 이상 풀기

**Comment by Mandory** [comment]
# 회고
12월은 월간 계획에 올렸던 내용 중 반만 성취하였네요.
1일에 Commit 2개를 끝으로 더 올리지 못하였고 :sweat_smile:, 알고리즘 인터넷 강의 3개 이상 듣기는 다행히 완료하였습니다.
2020년은 세상(?)도 많이 변했지만 개인적으로도 많이 변했던 한 해였던 것 같아요~ 이렇게 git을 이용한 스터디를 시작했으니말이예요!! 다들 2020년 한 해 수고 많으셨어용 ❤️ 

1월에도 알고리즘 공부를 꾸준히 하는 걸 목표로 하겠습니다. :heart_eyes_cat:

# 목표
* 알고리즘 인터넷 강의 듣기 -> 백준 문제풀이 후, Commit 올리기
* 개발 관련 서적 읽기
