### ISSUE TITLE
11월 스터디 진행

### ISSUE THREAD

**Issue by kuongee** [Mandory/my-js#7]
안녕하세요. 꾸옹입니다.

벌써 10월 마지막 주가 되었습니다.
스터디 목표인 **한달에 최소 3개 커밋 올리기**가 잘 지켜진 것 같아서 뿌듯합니당🥰

회고 및 다음달 목표 설정 조절 등을 위한 이슈를 오픈합니다.
다음달 목표도 우선 한달 최소 3개 커밋을 기본으로 하려고 합니다.
그런데 10월 스터디하면서 어려웠던 점이 있었다면 11월 스터디에는 조절하여 반영하면 좋겠습니다.
또는 다음달 스터디에 추가했으면 하는 목표가 있다면 댓글로 달아주세요!!

감사합니다.

**Comment by kuongee** [comment]
저는 이번달에 개인적으로 이력 또는 포트폴리오 정리하려고 합니다.
혹시 함께 하기 원하신다면 이번달 목표에 넣어보아요!
아니면 토이프로젝트도 좋아요!

**Comment by Mandory** [comment]
저는 그럼 11월에 알고리즘 꾸준히 공부해서 프로 시험에 한번 이상 응시하는 걸 목표로 할게요~
포트폴리오 정리해서 우리 11월에도 도전해보도록 해요!

**Comment by tildev** [comment]
안녕하세요! 틸뎁입니다.☺

**Comment by kuongee** [comment]
11월 말이 되어 이슈를 닫겠습니다.
